base:
  seed: 77
  model_arc: 'xception'
  image_size: 256
  batch_size: 16
  num_classes: 1
  ckpt_dir: './checkpoints/'
  use_kfold: True
  num_fold: 4


swin:
  seed: 77
  model_arc: 'swin_small_patch4_window7_224'
  image_size: 224
  batch_size: 16
  num_classes: 1
  ckpt_dir: './checkpoints/'
  use_kfold: False
  num_fold: 0


b0:
  seed: 77
  model_arc: 'efficientnet_b0'
  image_size: 256
  batch_size: 16
  num_classes: 1
  ckpt_dir: './checkpoints/'
  use_kfold: True
  num_fold: 5